export enum StatusServicePointPayment {
  NEW = 'NEW',
  ADVANCED = 'ADVANCED',
  PER_DAY = 'PER_DAY',
  OVERDUE = 'OVERDUE',
  NO_SERVICE = 'NO_SERVICE',
  SUSPENDED = 'SUSPENDED',
  NOT_CONTRIBUTING = 'NOT_CONTRIBUTING',
}
